cls
echo off
echo.
echo.
echo This demo of Crusader runs best with 16MB of RAM.
echo It's possible, on some machines, to run the 
echo demo with just 8MB of RAM. You'll probably HAVE
echo to create a boot disk that will create as much
echo free XMS memory as possible (7MB of free XMS is
echo needed). Check the system requirements to make sure
echo you make the grade.
echo.
pause
CD\CRUSADER
CALL INSTALL.EXE
PAUSE
